# Generated by Django 5.2.8 on 2025-11-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-priority', 'deadline']},
        ),
        migrations.AlterField(
            model_name='goal',
            name='priority',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('missed', 'Missed'), ('paused', 'Paused')], default='active', max_length=20),
        ),
    ]
