# Generated by Django 6.0.3 on 2026-04-13 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupinvite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupinvite',
            options={},
        ),
    ]
